// ── PRODUCTS DATABASE ─ 200+ prodotti con immagini ──
// Immagini food: TheMealDB CDN (sfondo bianco, stile pulito)
// Immagini non-food: Twemoji CDN (icone consistenti)
const PRODUCTS_DB = [
  // ═══════════════════════════════════════════════════
  // FRUTTA
  // ═══════════════════════════════════════════════════
  { name:"Mele", cat:"Frutta e Verdura", emoji:"🍎", img:"https://www.themealdb.com/images/ingredients/Apple-Small.png" },
  { name:"Mele Golden", cat:"Frutta e Verdura", emoji:"🍎", img:"https://www.themealdb.com/images/ingredients/Apple-Small.png" },
  { name:"Banane", cat:"Frutta e Verdura", emoji:"🍌", img:"https://www.themealdb.com/images/ingredients/Banana-Small.png" },
  { name:"Arance", cat:"Frutta e Verdura", emoji:"🍊", img:"https://www.themealdb.com/images/ingredients/Oranges-Small.png" },
  { name:"Limoni", cat:"Frutta e Verdura", emoji:"🍋", img:"https://www.themealdb.com/images/ingredients/Lemon-Small.png" },
  { name:"Pere", cat:"Frutta e Verdura", emoji:"🍐", img:"https://www.themealdb.com/images/ingredients/Pear-Small.png" },
  { name:"Pesche", cat:"Frutta e Verdura", emoji:"🍑", img:"https://www.themealdb.com/images/ingredients/Peaches-Small.png" },
  { name:"Albicocche", cat:"Frutta e Verdura", emoji:"🍑", img:"https://www.themealdb.com/images/ingredients/Apricots-Small.png" },
  { name:"Fragole", cat:"Frutta e Verdura", emoji:"🍓", img:"https://www.themealdb.com/images/ingredients/Strawberries-Small.png" },
  { name:"Mirtilli", cat:"Frutta e Verdura", emoji:"🫐", img:"https://www.themealdb.com/images/ingredients/Blueberries-Small.png" },
  { name:"Lamponi", cat:"Frutta e Verdura", emoji:"🫐", img:"https://www.themealdb.com/images/ingredients/Raspberries-Small.png" },
  { name:"Uva", cat:"Frutta e Verdura", emoji:"🍇", img:"https://www.themealdb.com/images/ingredients/Grapes-Small.png" },
  { name:"Ciliegie", cat:"Frutta e Verdura", emoji:"🍒", img:"https://www.themealdb.com/images/ingredients/Cherries-Small.png" },
  { name:"Kiwi", cat:"Frutta e Verdura", emoji:"🥝", img:"https://www.themealdb.com/images/ingredients/Kiwi-Small.png" },
  { name:"Ananas", cat:"Frutta e Verdura", emoji:"🍍", img:"https://www.themealdb.com/images/ingredients/Pineapple-Small.png" },
  { name:"Mango", cat:"Frutta e Verdura", emoji:"🥭", img:"https://www.themealdb.com/images/ingredients/Mango-Small.png" },
  { name:"Anguria", cat:"Frutta e Verdura", emoji:"🍉", img:"https://www.themealdb.com/images/ingredients/Watermelon-Small.png" },
  { name:"Melone", cat:"Frutta e Verdura", emoji:"🍈", img:"https://www.themealdb.com/images/ingredients/Melon-Small.png" },
  { name:"Avocado", cat:"Frutta e Verdura", emoji:"🥑", img:"https://www.themealdb.com/images/ingredients/Avocado-Small.png" },
  { name:"Cocco", cat:"Frutta e Verdura", emoji:"🥥", img:"https://www.themealdb.com/images/ingredients/Coconut-Small.png" },

  // ═══════════════════════════════════════════════════
  // VERDURA
  // ═══════════════════════════════════════════════════
  { name:"Pomodori", cat:"Frutta e Verdura", emoji:"🍅", img:"https://www.themealdb.com/images/ingredients/Tomatoes-Small.png" },
  { name:"Pomodorini", cat:"Frutta e Verdura", emoji:"🍅", img:"https://www.themealdb.com/images/ingredients/Cherry Tomatoes-Small.png" },
  { name:"Zucchine", cat:"Frutta e Verdura", emoji:"🥒", img:"https://www.themealdb.com/images/ingredients/Zucchini-Small.png" },
  { name:"Melanzane", cat:"Frutta e Verdura", emoji:"🍆", img:"https://www.themealdb.com/images/ingredients/Aubergine-Small.png" },
  { name:"Peperoni", cat:"Frutta e Verdura", emoji:"🫑", img:"https://www.themealdb.com/images/ingredients/Red Pepper-Small.png" },
  { name:"Carote", cat:"Frutta e Verdura", emoji:"🥕", img:"https://www.themealdb.com/images/ingredients/Carrots-Small.png" },
  { name:"Patate", cat:"Frutta e Verdura", emoji:"🥔", img:"https://www.themealdb.com/images/ingredients/Potatoes-Small.png" },
  { name:"Cipolle", cat:"Frutta e Verdura", emoji:"🧅", img:"https://www.themealdb.com/images/ingredients/Onion-Small.png" },
  { name:"Cipolla rossa", cat:"Frutta e Verdura", emoji:"🧅", img:"https://www.themealdb.com/images/ingredients/Red Onions-Small.png" },
  { name:"Aglio", cat:"Frutta e Verdura", emoji:"🧄", img:"https://www.themealdb.com/images/ingredients/Garlic-Small.png" },
  { name:"Insalata", cat:"Frutta e Verdura", emoji:"🥬", img:"https://www.themealdb.com/images/ingredients/Lettuce-Small.png" },
  { name:"Spinaci", cat:"Frutta e Verdura", emoji:"🥬", img:"https://www.themealdb.com/images/ingredients/Spinach-Small.png" },
  { name:"Broccoli", cat:"Frutta e Verdura", emoji:"🥦", img:"https://www.themealdb.com/images/ingredients/Broccoli-Small.png" },
  { name:"Cavolfiore", cat:"Frutta e Verdura", emoji:"🥦", img:"https://www.themealdb.com/images/ingredients/Cauliflower-Small.png" },
  { name:"Cavolo", cat:"Frutta e Verdura", emoji:"🥬", img:"https://www.themealdb.com/images/ingredients/Cabbage-Small.png" },
  { name:"Funghi", cat:"Frutta e Verdura", emoji:"🍄", img:"https://www.themealdb.com/images/ingredients/Mushrooms-Small.png" },
  { name:"Cetrioli", cat:"Frutta e Verdura", emoji:"🥒", img:"https://www.themealdb.com/images/ingredients/Cucumber-Small.png" },
  { name:"Sedano", cat:"Frutta e Verdura", emoji:"🥬", img:"https://www.themealdb.com/images/ingredients/Celery-Small.png" },
  { name:"Finocchio", cat:"Frutta e Verdura", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Fennel-Small.png" },
  { name:"Rucola", cat:"Frutta e Verdura", emoji:"🥬", img:"https://www.themealdb.com/images/ingredients/Rocket-Small.png" },
  { name:"Basilico", cat:"Frutta e Verdura", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Basil-Small.png" },
  { name:"Prezzemolo", cat:"Frutta e Verdura", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Parsley-Small.png" },
  { name:"Rosmarino", cat:"Frutta e Verdura", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Rosemary-Small.png" },
  { name:"Radicchio", cat:"Frutta e Verdura", emoji:"🥬", img:"https://www.themealdb.com/images/ingredients/Lettuce-Small.png" },
  { name:"Piselli", cat:"Frutta e Verdura", emoji:"🟢", img:"https://www.themealdb.com/images/ingredients/Peas-Small.png" },
  { name:"Zenzero", cat:"Frutta e Verdura", emoji:"🫚", img:"https://www.themealdb.com/images/ingredients/Ginger-Small.png" },
  { name:"Mais", cat:"Frutta e Verdura", emoji:"🌽", img:"https://www.themealdb.com/images/ingredients/Corn-Small.png" },
  { name:"Asparagi", cat:"Frutta e Verdura", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Asparagus-Small.png" },

  // ═══════════════════════════════════════════════════
  // LATTICINI E UOVA
  // ═══════════════════════════════════════════════════
  { name:"Latte intero", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Milk-Small.png" },
  { name:"Latte parzialmente scremato", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Milk-Small.png" },
  { name:"Latte scremato", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Milk-Small.png" },
  { name:"Latte di soia", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Soy Milk-Small.png" },
  { name:"Latte di mandorla", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Almond Milk-Small.png" },
  { name:"Latte di avena", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Oat Milk-Small.png" },
  { name:"Yogurt bianco", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Yogurt-Small.png" },
  { name:"Yogurt alla frutta", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Yogurt-Small.png" },
  { name:"Yogurt greco", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Greek Yogurt-Small.png" },
  { name:"Burro", cat:"Latticini e Uova", emoji:"🧈", img:"https://www.themealdb.com/images/ingredients/Butter-Small.png" },
  { name:"Panna fresca", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Heavy Cream-Small.png" },
  { name:"Panna da cucina", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Double Cream-Small.png" },
  { name:"Mozzarella", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Mozzarella-Small.png" },
  { name:"Parmigiano Reggiano", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Parmesan-Small.png" },
  { name:"Grana Padano", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Parmesan-Small.png" },
  { name:"Ricotta", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Ricotta-Small.png" },
  { name:"Mascarpone", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Mascarpone-Small.png" },
  { name:"Gorgonzola", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Blue Cheese-Small.png" },
  { name:"Pecorino", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Pecorino-Small.png" },
  { name:"Stracchino", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Cream Cheese-Small.png" },
  { name:"Philadelphia", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Cream Cheese-Small.png" },
  { name:"Provola", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Cheese-Small.png" },
  { name:"Scamorza", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Cheese-Small.png" },
  { name:"Emmental", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Emmental-Small.png" },
  { name:"Brie", cat:"Latticini e Uova", emoji:"🧀", img:"https://www.themealdb.com/images/ingredients/Brie-Small.png" },
  { name:"Uova", cat:"Latticini e Uova", emoji:"🥚", img:"https://www.themealdb.com/images/ingredients/Eggs-Small.png" },
  { name:"Latte Bio", cat:"Latticini e Uova", emoji:"🥛", img:"https://www.themealdb.com/images/ingredients/Milk-Small.png" },

  // ═══════════════════════════════════════════════════
  // CARNE E PESCE
  // ═══════════════════════════════════════════════════
  { name:"Petto di pollo", cat:"Carne e Pesce", emoji:"🍗", img:"https://www.themealdb.com/images/ingredients/Chicken Breast-Small.png" },
  { name:"Cosce di pollo", cat:"Carne e Pesce", emoji:"🍗", img:"https://www.themealdb.com/images/ingredients/Chicken Thighs-Small.png" },
  { name:"Pollo intero", cat:"Carne e Pesce", emoji:"🍗", img:"https://www.themealdb.com/images/ingredients/Chicken-Small.png" },
  { name:"Macinato di manzo", cat:"Carne e Pesce", emoji:"🥩", img:"https://www.themealdb.com/images/ingredients/Minced Beef-Small.png" },
  { name:"Bistecca di manzo", cat:"Carne e Pesce", emoji:"🥩", img:"https://www.themealdb.com/images/ingredients/Beef-Small.png" },
  { name:"Fettine di vitello", cat:"Carne e Pesce", emoji:"🥩", img:"https://www.themealdb.com/images/ingredients/Beef-Small.png" },
  { name:"Salsiccia", cat:"Carne e Pesce", emoji:"🌭", img:"https://www.themealdb.com/images/ingredients/Sausages-Small.png" },
  { name:"Prosciutto cotto", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Ham-Small.png" },
  { name:"Prosciutto crudo", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Prosciutto-Small.png" },
  { name:"Salame", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Salami-Small.png" },
  { name:"Bresaola", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Beef-Small.png" },
  { name:"Mortadella", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Ham-Small.png" },
  { name:"Pancetta", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Bacon-Small.png" },
  { name:"Speck", cat:"Carne e Pesce", emoji:"🥓", img:"https://www.themealdb.com/images/ingredients/Bacon-Small.png" },
  { name:"Wurstel", cat:"Carne e Pesce", emoji:"🌭", img:"https://www.themealdb.com/images/ingredients/Sausages-Small.png" },
  { name:"Cotolette", cat:"Carne e Pesce", emoji:"🍗", img:"https://www.themealdb.com/images/ingredients/Chicken Breast-Small.png" },
  { name:"Macinato di maiale", cat:"Carne e Pesce", emoji:"🥩", img:"https://www.themealdb.com/images/ingredients/Pork-Small.png" },
  { name:"Tacchino", cat:"Carne e Pesce", emoji:"🍗", img:"https://www.themealdb.com/images/ingredients/Turkey-Small.png" },
  { name:"Tonno in scatola", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Tuna-Small.png" },
  { name:"Salmone", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Salmon-Small.png" },
  { name:"Merluzzo", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Cod-Small.png" },
  { name:"Gamberetti", cat:"Carne e Pesce", emoji:"🦐", img:"https://www.themealdb.com/images/ingredients/Prawns-Small.png" },
  { name:"Baccalà", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Cod-Small.png" },
  { name:"Polpo", cat:"Carne e Pesce", emoji:"🐙", img:"https://www.themealdb.com/images/ingredients/Squid-Small.png" },
  { name:"Calamari", cat:"Carne e Pesce", emoji:"🦑", img:"https://www.themealdb.com/images/ingredients/Squid-Small.png" },
  { name:"Acciughe", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Anchovies-Small.png" },
  { name:"Sardine", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Sardines-Small.png" },
  { name:"Orata", cat:"Carne e Pesce", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Sea Bass-Small.png" },
  { name:"Vongole", cat:"Carne e Pesce", emoji:"🐚", img:"https://www.themealdb.com/images/ingredients/Clams-Small.png" },
  { name:"Cozze", cat:"Carne e Pesce", emoji:"🐚", img:"https://www.themealdb.com/images/ingredients/Mussels-Small.png" },

  // ═══════════════════════════════════════════════════
  // DISPENSA
  // ═══════════════════════════════════════════════════
  { name:"Pasta", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Pasta-Small.png" },
  { name:"Pasta di semola", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Pasta-Small.png" },
  { name:"Penne", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Penne-Small.png" },
  { name:"Spaghetti", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Spaghetti-Small.png" },
  { name:"Fusilli", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Fusilli-Small.png" },
  { name:"Rigatoni", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Rigatoni-Small.png" },
  { name:"Lasagne", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Lasagne Sheets-Small.png" },
  { name:"Farfalle", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Farfalle-Small.png" },
  { name:"Pasta Garofalo", cat:"Dispensa", emoji:"🍝", img:"https://www.themealdb.com/images/ingredients/Pasta-Small.png" },
  { name:"Riso Carnaroli", cat:"Dispensa", emoji:"🍚", img:"https://www.themealdb.com/images/ingredients/Rice-Small.png" },
  { name:"Riso Basmati", cat:"Dispensa", emoji:"🍚", img:"https://www.themealdb.com/images/ingredients/Basmati Rice-Small.png" },
  { name:"Riso Arborio", cat:"Dispensa", emoji:"🍚", img:"https://www.themealdb.com/images/ingredients/Arborio Rice-Small.png" },
  { name:"Farina 00", cat:"Dispensa", emoji:"🌾", img:"https://www.themealdb.com/images/ingredients/Plain Flour-Small.png" },
  { name:"Farina integrale", cat:"Dispensa", emoji:"🌾", img:"https://www.themealdb.com/images/ingredients/Wholemeal Flour-Small.png" },
  { name:"Pane bianco", cat:"Dispensa", emoji:"🍞", img:"https://www.themealdb.com/images/ingredients/Bread-Small.png" },
  { name:"Pane integrale", cat:"Dispensa", emoji:"🍞", img:"https://www.themealdb.com/images/ingredients/Bread-Small.png" },
  { name:"Pancarrè", cat:"Dispensa", emoji:"🍞", img:"https://www.themealdb.com/images/ingredients/Bread-Small.png" },
  { name:"Grissini", cat:"Dispensa", emoji:"🥖", img:"https://www.themealdb.com/images/ingredients/Breadsticks-Small.png" },
  { name:"Crackers", cat:"Dispensa", emoji:"🍪", img:"https://www.themealdb.com/images/ingredients/Crackers-Small.png" },
  { name:"Fette biscottate", cat:"Dispensa", emoji:"🍞", img:"https://www.themealdb.com/images/ingredients/Bread-Small.png" },
  { name:"Biscotti", cat:"Dispensa", emoji:"🍪", img:"https://www.themealdb.com/images/ingredients/Biscuits-Small.png" },
  { name:"Cereali", cat:"Dispensa", emoji:"🥣", img:"https://www.themealdb.com/images/ingredients/Cereal-Small.png" },
  { name:"Muesli", cat:"Dispensa", emoji:"🥣", img:"https://www.themealdb.com/images/ingredients/Muesli-Small.png" },
  { name:"Avena", cat:"Dispensa", emoji:"🌾", img:"https://www.themealdb.com/images/ingredients/Oats-Small.png" },
  { name:"Olio extravergine", cat:"Dispensa", emoji:"🫒", img:"https://www.themealdb.com/images/ingredients/Olive Oil-Small.png" },
  { name:"Olio di semi", cat:"Dispensa", emoji:"🫙", img:"https://www.themealdb.com/images/ingredients/Vegetable Oil-Small.png" },
  { name:"Aceto balsamico", cat:"Dispensa", emoji:"🫙", img:"https://www.themealdb.com/images/ingredients/Balsamic Vinegar-Small.png" },
  { name:"Aceto di vino", cat:"Dispensa", emoji:"🫙", img:"https://www.themealdb.com/images/ingredients/Red Wine Vinegar-Small.png" },
  { name:"Sale fino", cat:"Dispensa", emoji:"🧂", img:"https://www.themealdb.com/images/ingredients/Salt-Small.png" },
  { name:"Sale grosso", cat:"Dispensa", emoji:"🧂", img:"https://www.themealdb.com/images/ingredients/Salt-Small.png" },
  { name:"Pepe nero", cat:"Dispensa", emoji:"🧂", img:"https://www.themealdb.com/images/ingredients/Pepper-Small.png" },
  { name:"Zucchero", cat:"Dispensa", emoji:"🍬", img:"https://www.themealdb.com/images/ingredients/Sugar-Small.png" },
  { name:"Zucchero di canna", cat:"Dispensa", emoji:"🍬", img:"https://www.themealdb.com/images/ingredients/Brown Sugar-Small.png" },
  { name:"Miele", cat:"Dispensa", emoji:"🍯", img:"https://www.themealdb.com/images/ingredients/Honey-Small.png" },
  { name:"Marmellata", cat:"Dispensa", emoji:"🍓", img:"https://www.themealdb.com/images/ingredients/Jam-Small.png" },
  { name:"Nutella", cat:"Dispensa", emoji:"🍫", img:"https://www.themealdb.com/images/ingredients/Nutella-Small.png" },
  { name:"Passata di pomodoro", cat:"Dispensa", emoji:"🍅", img:"https://www.themealdb.com/images/ingredients/Passata-Small.png" },
  { name:"Pelati", cat:"Dispensa", emoji:"🍅", img:"https://www.themealdb.com/images/ingredients/Chopped Tomatoes-Small.png" },
  { name:"Polpa di pomodoro", cat:"Dispensa", emoji:"🍅", img:"https://www.themealdb.com/images/ingredients/Chopped Tomatoes-Small.png" },
  { name:"Concentrato di pomodoro", cat:"Dispensa", emoji:"🍅", img:"https://www.themealdb.com/images/ingredients/Tomato Puree-Small.png" },
  { name:"Pesto alla genovese", cat:"Dispensa", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Pesto-Small.png" },
  { name:"Dado", cat:"Dispensa", emoji:"🧊", img:"https://www.themealdb.com/images/ingredients/Vegetable Stock Cube-Small.png" },
  { name:"Brodo", cat:"Dispensa", emoji:"🍲", img:"https://www.themealdb.com/images/ingredients/Vegetable Stock-Small.png" },
  { name:"Lenticchie", cat:"Dispensa", emoji:"🫘", img:"https://www.themealdb.com/images/ingredients/Lentils-Small.png" },
  { name:"Ceci", cat:"Dispensa", emoji:"🫘", img:"https://www.themealdb.com/images/ingredients/Chickpeas-Small.png" },
  { name:"Fagioli", cat:"Dispensa", emoji:"🫘", img:"https://www.themealdb.com/images/ingredients/Kidney Beans-Small.png" },
  { name:"Fagioli borlotti", cat:"Dispensa", emoji:"🫘", img:"https://www.themealdb.com/images/ingredients/Borlotti Beans-Small.png" },
  { name:"Cannellini", cat:"Dispensa", emoji:"🫘", img:"https://www.themealdb.com/images/ingredients/Cannellini Beans-Small.png" },
  { name:"Tonno sott'olio", cat:"Dispensa", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Tuna-Small.png" },
  { name:"Cous cous", cat:"Dispensa", emoji:"🍚", img:"https://www.themealdb.com/images/ingredients/Cous Cous-Small.png" },
  { name:"Lievito", cat:"Dispensa", emoji:"🧁", img:"https://www.themealdb.com/images/ingredients/Yeast-Small.png" },
  { name:"Pangrattato", cat:"Dispensa", emoji:"🍞", img:"https://www.themealdb.com/images/ingredients/Breadcrumbs-Small.png" },
  { name:"Maionese", cat:"Dispensa", emoji:"🥫", img:"https://www.themealdb.com/images/ingredients/Mayonnaise-Small.png" },
  { name:"Ketchup", cat:"Dispensa", emoji:"🥫", img:"https://www.themealdb.com/images/ingredients/Tomato Ketchup-Small.png" },
  { name:"Senape", cat:"Dispensa", emoji:"🥫", img:"https://www.themealdb.com/images/ingredients/Mustard-Small.png" },
  { name:"Salsa di soia", cat:"Dispensa", emoji:"🥫", img:"https://www.themealdb.com/images/ingredients/Soy Sauce-Small.png" },
  { name:"Cioccolato fondente", cat:"Dispensa", emoji:"🍫", img:"https://www.themealdb.com/images/ingredients/Dark Chocolate-Small.png" },
  { name:"Cioccolato al latte", cat:"Dispensa", emoji:"🍫", img:"https://www.themealdb.com/images/ingredients/Milk Chocolate-Small.png" },
  { name:"Cacao in polvere", cat:"Dispensa", emoji:"🍫", img:"https://www.themealdb.com/images/ingredients/Cocoa-Small.png" },
  { name:"Olive", cat:"Dispensa", emoji:"🫒", img:"https://www.themealdb.com/images/ingredients/Olives-Small.png" },
  { name:"Capperi", cat:"Dispensa", emoji:"🌿", img:"https://www.themealdb.com/images/ingredients/Capers-Small.png" },
  { name:"Sottaceti", cat:"Dispensa", emoji:"🥒", img:"https://www.themealdb.com/images/ingredients/Gherkins-Small.png" },
  { name:"Mandorle", cat:"Dispensa", emoji:"🥜", img:"https://www.themealdb.com/images/ingredients/Almonds-Small.png" },
  { name:"Noci", cat:"Dispensa", emoji:"🥜", img:"https://www.themealdb.com/images/ingredients/Walnuts-Small.png" },
  { name:"Nocciole", cat:"Dispensa", emoji:"🥜", img:"https://www.themealdb.com/images/ingredients/Hazelnuts-Small.png" },
  { name:"Pinoli", cat:"Dispensa", emoji:"🥜", img:"https://www.themealdb.com/images/ingredients/Pine Nuts-Small.png" },

  // ═══════════════════════════════════════════════════
  // BEVANDE
  // ═══════════════════════════════════════════════════
  { name:"Acqua naturale", cat:"Bevande", emoji:"💧", img:"https://www.themealdb.com/images/ingredients/Water-Small.png" },
  { name:"Acqua frizzante", cat:"Bevande", emoji:"💧", img:"https://www.themealdb.com/images/ingredients/Water-Small.png" },
  { name:"Succo d'arancia", cat:"Bevande", emoji:"🧃", img:"https://www.themealdb.com/images/ingredients/Orange Juice-Small.png" },
  { name:"Succo di mela", cat:"Bevande", emoji:"🧃", img:"https://www.themealdb.com/images/ingredients/Apple Juice-Small.png" },
  { name:"Succo di frutta", cat:"Bevande", emoji:"🧃", img:"https://www.themealdb.com/images/ingredients/Apple Juice-Small.png" },
  { name:"Coca Cola", cat:"Bevande", emoji:"🥤", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f964.png" },
  { name:"Aranciata", cat:"Bevande", emoji:"🥤", img:"https://www.themealdb.com/images/ingredients/Orange Juice-Small.png" },
  { name:"Tè freddo", cat:"Bevande", emoji:"🧊", img:"https://www.themealdb.com/images/ingredients/Iced Tea-Small.png" },
  { name:"Birra", cat:"Bevande", emoji:"🍺", img:"https://www.themealdb.com/images/ingredients/Beer-Small.png" },
  { name:"Vino rosso", cat:"Bevande", emoji:"🍷", img:"https://www.themealdb.com/images/ingredients/Red Wine-Small.png" },
  { name:"Vino bianco", cat:"Bevande", emoji:"🍷", img:"https://www.themealdb.com/images/ingredients/White Wine-Small.png" },
  { name:"Prosecco", cat:"Bevande", emoji:"🥂", img:"https://www.themealdb.com/images/ingredients/White Wine-Small.png" },
  { name:"Caffè macinato", cat:"Bevande", emoji:"☕", img:"https://www.themealdb.com/images/ingredients/Coffee-Small.png" },
  { name:"Caffè in capsule", cat:"Bevande", emoji:"☕", img:"https://www.themealdb.com/images/ingredients/Coffee-Small.png" },
  { name:"Caffè", cat:"Bevande", emoji:"☕", img:"https://www.themealdb.com/images/ingredients/Coffee-Small.png" },
  { name:"Tè verde", cat:"Bevande", emoji:"🍵", img:"https://www.themealdb.com/images/ingredients/Green Tea-Small.png" },
  { name:"Tisana", cat:"Bevande", emoji:"🍵", img:"https://www.themealdb.com/images/ingredients/Tea-Small.png" },
  { name:"Camomilla", cat:"Bevande", emoji:"🍵", img:"https://www.themealdb.com/images/ingredients/Tea-Small.png" },
  { name:"Limonata", cat:"Bevande", emoji:"🍋", img:"https://www.themealdb.com/images/ingredients/Lemon Juice-Small.png" },
  { name:"Sprite", cat:"Bevande", emoji:"🥤", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f964.png" },
  { name:"Energy drink", cat:"Bevande", emoji:"⚡", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/26a1.png" },
  { name:"Latte di cocco", cat:"Bevande", emoji:"🥥", img:"https://www.themealdb.com/images/ingredients/Coconut Milk-Small.png" },

  // ═══════════════════════════════════════════════════
  // SURGELATI E SNACK
  // ═══════════════════════════════════════════════════
  { name:"Pizza surgelata", cat:"Altro", emoji:"🍕", img:"https://www.themealdb.com/images/ingredients/Pizza-Small.png" },
  { name:"Gelato", cat:"Altro", emoji:"🍦", img:"https://www.themealdb.com/images/ingredients/Ice Cream-Small.png" },
  { name:"Bastoncini di pesce", cat:"Altro", emoji:"🐟", img:"https://www.themealdb.com/images/ingredients/Fish Fingers-Small.png" },
  { name:"Verdure surgelate", cat:"Altro", emoji:"🥦", img:"https://www.themealdb.com/images/ingredients/Mixed Vegetables-Small.png" },
  { name:"Patate fritte surgelate", cat:"Altro", emoji:"🍟", img:"https://www.themealdb.com/images/ingredients/Chips-Small.png" },
  { name:"Patatine chips", cat:"Altro", emoji:"🍟", img:"https://www.themealdb.com/images/ingredients/Crisps-Small.png" },
  { name:"Caramelle", cat:"Altro", emoji:"🍬", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f36c.png" },
  { name:"Torta", cat:"Altro", emoji:"🎂", img:"https://www.themealdb.com/images/ingredients/Cake-Small.png" },
  { name:"Croissant", cat:"Altro", emoji:"🥐", img:"https://www.themealdb.com/images/ingredients/Croissants-Small.png" },
  { name:"Merendine", cat:"Altro", emoji:"🍰", img:"https://www.themealdb.com/images/ingredients/Cake-Small.png" },
  { name:"Pop corn", cat:"Altro", emoji:"🍿", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f37f.png" },
  { name:"Tofu", cat:"Altro", emoji:"🥡", img:"https://www.themealdb.com/images/ingredients/Tofu-Small.png" },
  { name:"Hummus", cat:"Altro", emoji:"🫘", img:"https://www.themealdb.com/images/ingredients/Houmous-Small.png" },
  { name:"Burro d'arachidi", cat:"Altro", emoji:"🥜", img:"https://www.themealdb.com/images/ingredients/Peanut Butter-Small.png" },
  { name:"Tortillas", cat:"Altro", emoji:"🌮", img:"https://www.themealdb.com/images/ingredients/Tortillas-Small.png" },

  // ═══════════════════════════════════════════════════
  // CASA E IGIENE (Twemoji icons)
  // ═══════════════════════════════════════════════════
  { name:"Carta igienica", cat:"Casa", emoji:"🧻", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9fb.png" },
  { name:"Scottex", cat:"Casa", emoji:"🧻", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9fb.png" },
  { name:"Detersivo piatti", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Detersivo lavatrice", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Ammorbidente", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Sapone mani", cat:"Casa", emoji:"🧼", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9fc.png" },
  { name:"Shampoo", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Bagnoschiuma", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Dentifricio", cat:"Casa", emoji:"🪥", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1faa5.png" },
  { name:"Spazzolino", cat:"Casa", emoji:"🪥", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1faa5.png" },
  { name:"Tovaglioli", cat:"Casa", emoji:"🧻", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9fb.png" },
  { name:"Pellicola", cat:"Casa", emoji:"📦", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4e6.png" },
  { name:"Alluminio", cat:"Casa", emoji:"📦", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4e6.png" },
  { name:"Sacchetti spazzatura", cat:"Casa", emoji:"🗑️", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f5d1.png" },
  { name:"Spugne", cat:"Casa", emoji:"🧽", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9fd.png" },
  { name:"Candeggina", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Sgrassatore", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Crema idratante", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Cotton fioc", cat:"Casa", emoji:"🏥", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f3e5.png" },
  { name:"Fazzoletti", cat:"Casa", emoji:"🤧", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f927.png" },
  { name:"Disinfettante", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Guanti", cat:"Casa", emoji:"🧤", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9e4.png" },
  { name:"Deodorante", cat:"Casa", emoji:"🧴", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9f4.png" },
  { name:"Rasoio", cat:"Casa", emoji:"🪒", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1fa92.png" },
  { name:"Sapone di Marsiglia", cat:"Casa", emoji:"🧼", img:"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f9fc.png" },
];

// Quick lookup by normalized name
const PRODUCTS_LOOKUP = {};
PRODUCTS_DB.forEach(p => {
  PRODUCTS_LOOKUP[p.name.toLowerCase()] = p;
});

// Search products by query string (fuzzy)
function searchProducts(query) {
  if (!query) return [];
  const q = query.toLowerCase().trim();
  return PRODUCTS_DB.filter(p => p.name.toLowerCase().includes(q));
}

// Get product info from DB by name
function getProductInfo(name) {
  return PRODUCTS_LOOKUP[name.toLowerCase().trim()] || null;
}
